name=RemoteUpload
version=1.0.0
author=Idlan Zafran Mohd Zaidie
maintainer=Idlan Zafran Mohd Zaidie <lanzaidie@gmail.com>
sentence=Effortless Local and Remote (Google Drive) OTA updates for ESP32 and ESP8266.
paragraph=A wrapper library that seamlessly handles both traditional local IDE OTA updates and remote firmware updates directly from Google Drive share links. Includes a convenient serial trigger mechanism for easy testing.
category=Communication
url=https://github.com/IdlanZafran/RemoteUpload
architectures=esp32,esp8266
